name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci
      - run: npm run build

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: code/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: build success (POST)
        if: success()
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_SERVER_WEB_HOOK }}
        run: |
          curl -s -X POST -H 'Content-Type: application/json' \
            -d '{"content":"Build status: ✅","username": "$GITHUB_REPOSITORY_OWNER"}' \
            "$WEBHOOK_URL"

      - name: build failure (POST)
        if: failure()
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_SERVER_WEB_HOOK }}
        run: |
          curl -s -X POST -H 'Content-Type: application/json' \
            -d '{"content":"Build status: ❌","username": "$GITHUB_REPOSITORY_OWNER"}' \
            "$WEBHOOK_URL"
